drop __at_require_pkgname and speed up at_repoforpkg
whenever we use __at_require_pkgname we usually also use at_repoforpkg,
no need to run a slow find command twice (although it's less slow now
that i added the maxdepth, but still...)

diff --git a/apktoys b/apktoys
--- a/apktoys
+++ b/apktoys
@@ -46,34 +46,19 @@ __at_argparse() {
 	echo "$args:$params"
 }
 
-# `__at_require_pkgname` - checks if a pkgname was provided as an argument
-__at_require_pkgname() {
-	if [ ! $1 ]; then
-		echo "tool requires package name to be passed"
-		return 1
-	fi
-
-	for pkg in $*; do
-		if [ ! $(find "$APORTS_DIRECTORY" -name $pkg -type d) ]; then
-			echo "package '$pkg' not found"
-			return 1
-		fi
-	done
-
-	return 0
-}
-
 # `at-repoforpkg <package>` - returns a string like `repository/pkgname`.
 # usually used internally for the other commands, but may be useful in other
 # cases.
 at_repoforpkg() {
-	__at_require_pkgname $1 || return 1
-
 	case $1 in
 		*'/'*) echo "$1"; return 0;; # already in repository/pkgname format
 	esac
 
-	directory="$(find $APORTS_DIRECTORY -name $1 -type d | head -n1)"
+	directory="$(find $APORTS_DIRECTORY -name $1 -type d -maxdepth 2 | head -n1)"
+	if [ ! "$directory" ]; then
+		echo "Package $1 not found" 1>&2
+		exit 1
+	fi
 	clean_name="${directory/$APORTS_DIRECTORY/}"
 
 	if [ "${clean_name::1}" = '/' ]; then
@@ -103,9 +88,7 @@ at_commit() {
 	raw_package="$(echo $argparse | cut -d ' ' -f2)"
 	data="$(echo $argparse | cut -d ' ' -f3)"
 
-	__at_require_pkgname $raw_package
-
-	package="$(at_repoforpkg $raw_package)"
+	package="$(at_repoforpkg $raw_package)" || exit 1
 
 	case $template in
 		'upgrade') msg="$package: upgrade to $data";;
@@ -127,7 +110,6 @@ at_newpkg() {
 	args="$(echo $argparse | cut -d: -f1)"
 	pkgs="${argparse##$args:}"
 
-	__at_require_pkgname $pkgs || return 1
 	__at_cd_aports
 
 	if [ $2 ]; then
@@ -138,7 +120,7 @@ at_newpkg() {
 	echo $pkgs
 
 	for pkg in $pkgs; do
-		pkg_with_repo="$(at_repoforpkg $pkg)"
+		pkg_with_repo="$(at_repoforpkg $pkg)" || exit 1;
 		git add "$APORTS_DIRECTORY/$pkg_with_repo"
 		cd "$APORTS_DIRECTORY/$pkg_with_repo"
 		source APKBUILD
