at-repoforpkg: add pwd handling
also fixes some problems introduced by the previous commit.

diff --git a/apktoys b/apktoys
--- a/apktoys
+++ b/apktoys
@@ -52,11 +52,14 @@ __at_argparse() {
 at_repoforpkg() {
 	case $1 in
 		*'/'*) echo "$1"; return 0;; # already in repository/pkgname format
+		'') return 1;; # no pkg provided
+		'pwd') pkgname=$(basename $PWD);;
+		*) pkgname=$1;;
 	esac
 
-	directory="$(find $APORTS_DIRECTORY -name $1 -type d -maxdepth 2 | head -n1)"
+	directory="$(find $APORTS_DIRECTORY -name $pkgname -type d -maxdepth 2 | head -n1)"
 	if [ ! "$directory" ]; then
-		echo "Package $1 not found" 1>&2
+		echo "Package $pkgname not found" 1>&2
 		exit 1
 	fi
 	clean_name="${directory/$APORTS_DIRECTORY/}"
@@ -90,10 +93,6 @@ at_commit() {
 	template="${template:1}" # strip leading :
 	raw_package="$(echo $argparse | cut -d ' ' -f2)"
 	data="$(echo $argparse | cut -d ' ' -f3)"
-
-	if [ $raw_package = 'pwd' ]; then
-		raw_package="$(basename $PWD)"
-	fi
 
 	package="$(at_repoforpkg $raw_package)" || exit 1
 
@@ -158,7 +157,7 @@ $pkgdesc"
 # `at-commit upgrade <package> (pkgver) [--amend/-m]`, you still need to do
 # everything else manually.
 at_upgrade() {
-	package=$(at_repoforpkg $package)
+	package=$(at_repoforpkg $1) || exit 1
 	source "$APORTS_DIRECTORY"/$package/APKBUILD
 	at_commit upgrade $package $pkgver $2
 }
